### PR TITLE
switch get_thumb to use context.wrap_socket

### LINKED ISSUE #517: Compute manager failes with
### Describe the bug

nsxt_fabric_compute_managers module generates the following error if used under Python 3.12.

```
AttributeError: module 'ssl' has no attribute 'wrap_socket'
```

This is because ssl_wrap_socket() has be deprecated since Python 3.7. See description of 
the issue [here](https://github.com/vmware/pyvmomi/issues/1057)

[Link to alternate implementation](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname).

### Reproduction steps

This bug appears if you try to use the nsxt_fabric_compute_managers with Python 3.12.

### Expected behavior

There is no error

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by laidbackware**
switch get_thumb to use context.wrap_socket
due to removal of ssl.wrap_socket in python 3.12
fixed mixed indentation and mixed variable naming to snake case, as per python standard

This fixes https://github.com/vmware/ansible-for-nsxt/issues/517

Tested as working in my lab

### CODE REVIEW

**Comment by laidbackware** [comment]
@ggverma can you please prioritise merging this, as these modules do not work using recent versions of Linux, including Ubuntu 24.04.

**Comment by ushiba0** [comment]
I noticed that ssl.wrap_socket() is also used in plugins/modules/nsxt_transport_nodes.py, specifically within the get_api_cert_thumbprint() function.
Because of this, ansible-for-next does not work with Python 3.12, and as a result, it also fails to run on Ubuntu 24.04. Since this module doesn't work on the latest OS versions, I believe we should consider raising the priority of this issue.
